name: Build

on: workflow_dispatch


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build and test wheels
        env:
          CIBW_SKIP: "pp* *-manylinux_i686"
        uses: pypa/cibuildwheel@v2.19.1
      
      - uses: actions/upload-artifact@v4
        env:
          CIBW_SKIP: "pp* *-manylinux_i686"
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
